# Generated by Django 3.1.2 on 2020-10-26 11:27

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0007_auto_20201025_1626'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='watchlists',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
