# Generated by Django 3.1.2 on 2020-10-26 11:29

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0008_listing_watchlists'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='watchlists',
            field=models.ManyToManyField(blank=True, related_name='listings_on_watchlist', to=settings.AUTH_USER_MODEL),
        ),
    ]
