# Generated by Django 3.1.2 on 2020-10-27 11:06

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0010_auto_20201027_1301'),
    ]

    operations = [
        migrations.AddField(
            model_name='bid',
            name='bid_datetime',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
