# Generated by Django 3.1.2 on 2020-10-30 13:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0016_auto_20201028_1724'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listing',
            name='watchlists',
        ),
    ]
